addons:
  apt:
    packages:
    - lib32stdc++6
    - lib32z1-dev
    - libc6-dev-i386
    - libc6-i386
    - linux-libc-dev
    - gcc-multilib
    - g++-multilib
    - ia32-libs
sudo: false
language: cpp
compiler:
  - clang
before_script:
  - CHECKOUT_DIR=$PWD && cd .. 
  - chmod a+x $CHECKOUT_DIR/support/checkout-deps.sh 
  - $CHECKOUT_DIR/support/checkout-deps.sh && cd $CHECKOUT_DIR
script:
  - mkdir build && cd build
  - PATH="~/.local/bin:$PATH"
  - python ../support/configure.py --enable-optimize
  - ambuild
