
version: 1.0.{build}

clone_folder: c:\projects\adminfreelook

branches:
  only:
    - master
    
skip_tags: true

install:
- 'c:'
- chdir c:\projects
- git clone https://github.com/alliedmodders/ambuild
- git clone https://github.com/alliedmodders/metamod-hl1 metamod-am
- git clone https://github.com/alliedmodders/hlsdk
- git clone --recursive https://github.com/alliedmodders/amxmodx
- cd ambuild
- c:\python27\python setup.py install
- cd ..\adminfreelook

build_script:
- '"%VS120COMNTOOLS%\vsvars32.bat"'
- mkdir build
- cd build
- c:\python27\python ../support/configure.py --enable-optimize
- c:\python27\scripts\ambuild

cache:
  - metamod-am
  - hlsdk

